-- =============================================================================
-- XenoPulse :: Core retail / loyalty schema
-- =============================================================================
-- ALL DATA GENERATED BY THIS PROJECT IS SYNTHETIC. See db/seed.sql.
--
-- Design notes
--   * BIGINT surrogate keys, contiguous from 1 (seed relies on this for fast
--     set-based generation).
--   * Money stored as NUMERIC(12,2). Never float.
--   * order_items.line_total and orders.gross/net are stored (denormalised) so
--     the analytics layer can demonstrate aggregation-optimisation trade-offs.
--   * This file creates ONLY tables + primary/unique/foreign keys.
--     Secondary indexes live in db/indexes.sql so the Query Performance Lab can
--     add / drop them and benchmark the difference.
-- =============================================================================

BEGIN;

DROP TABLE IF EXISTS campaign_events CASCADE;
DROP TABLE IF EXISTS order_items      CASCADE;
DROP TABLE IF EXISTS orders           CASCADE;
DROP TABLE IF EXISTS campaigns        CASCADE;
DROP TABLE IF EXISTS products         CASCADE;
DROP TABLE IF EXISTS customers        CASCADE;
DROP TABLE IF EXISTS etl_runs         CASCADE;

-- -----------------------------------------------------------------------------
-- customers
-- -----------------------------------------------------------------------------
CREATE TABLE customers (
    customer_id         BIGSERIAL PRIMARY KEY,
    full_name           TEXT        NOT NULL,
    email               TEXT,                       -- nullable on purpose (data-quality demo)
    city                TEXT,
    region              TEXT,
    country             TEXT        NOT NULL DEFAULT 'IN',
    acquisition_channel TEXT        NOT NULL,       -- organic | paid_search | social | referral | email
    signup_date         DATE        NOT NULL,
    birth_year          INT,                        -- nullable on purpose
    is_synthetic        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE customers IS 'Synthetic loyalty customers.';

-- -----------------------------------------------------------------------------
-- products
-- -----------------------------------------------------------------------------
CREATE TABLE products (
    product_id   BIGSERIAL PRIMARY KEY,
    sku          TEXT        NOT NULL,
    product_name TEXT        NOT NULL,
    category     TEXT        NOT NULL,
    subcategory  TEXT        NOT NULL,
    unit_price   NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    unit_cost    NUMERIC(10,2) NOT NULL CHECK (unit_cost  >= 0),
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    launch_date  DATE        NOT NULL,
    is_synthetic BOOLEAN     NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE products IS 'Synthetic product catalogue.';

-- -----------------------------------------------------------------------------
-- campaigns
-- -----------------------------------------------------------------------------
CREATE TABLE campaigns (
    campaign_id   BIGSERIAL PRIMARY KEY,
    campaign_name TEXT        NOT NULL,
    channel       TEXT        NOT NULL,   -- email | sms | push | social | paid_search
    objective     TEXT        NOT NULL,   -- acquisition | retention | winback | upsell
    start_date    DATE        NOT NULL,
    end_date      DATE        NOT NULL,
    budget        NUMERIC(12,2) NOT NULL CHECK (budget >= 0),
    is_synthetic  BOOLEAN     NOT NULL DEFAULT TRUE,
    CHECK (end_date >= start_date)
);
COMMENT ON TABLE campaigns IS 'Synthetic marketing campaigns.';

-- -----------------------------------------------------------------------------
-- orders
-- -----------------------------------------------------------------------------
CREATE TABLE orders (
    order_id        BIGSERIAL PRIMARY KEY,
    customer_id     BIGINT      NOT NULL REFERENCES customers (customer_id),
    order_date      TIMESTAMPTZ NOT NULL,
    status          TEXT        NOT NULL,   -- completed | returned | cancelled | pending
    channel         TEXT        NOT NULL,   -- web | mobile_app | store | marketplace
    ship_region     TEXT,
    discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    shipping_fee    NUMERIC(10,2) NOT NULL DEFAULT 0,
    gross_amount    NUMERIC(12,2) NOT NULL DEFAULT 0,   -- sum(order_items.line_total)
    net_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,   -- gross - discount + shipping
    campaign_id     BIGINT      REFERENCES campaigns (campaign_id),  -- attributed campaign (nullable)
    is_synthetic    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE orders IS 'Synthetic orders. net_amount is the revenue-bearing column.';

-- -----------------------------------------------------------------------------
-- order_items
-- -----------------------------------------------------------------------------
CREATE TABLE order_items (
    order_item_id BIGSERIAL PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders   (order_id),
    product_id    BIGINT      NOT NULL REFERENCES products (product_id),
    quantity      INT         NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    line_total    NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);
COMMENT ON TABLE order_items IS 'Synthetic order line items.';

-- -----------------------------------------------------------------------------
-- campaign_events  (the "big" table used for performance benchmarking)
-- -----------------------------------------------------------------------------
CREATE TABLE campaign_events (
    event_id    BIGSERIAL PRIMARY KEY,
    campaign_id BIGINT      NOT NULL REFERENCES campaigns (campaign_id),
    customer_id BIGINT      NOT NULL REFERENCES customers (customer_id),
    event_type  TEXT        NOT NULL,   -- sent | delivered | open | click | convert | unsubscribe
    event_time  TIMESTAMPTZ NOT NULL,
    order_id    BIGINT      REFERENCES orders (order_id),
    revenue     NUMERIC(12,2) NOT NULL DEFAULT 0
);
COMMENT ON TABLE campaign_events IS 'Synthetic campaign funnel events (sent -> open -> click -> convert).';

-- -----------------------------------------------------------------------------
-- etl_runs  (synthetic pipeline log -- powers Data Quality > pipeline status)
-- -----------------------------------------------------------------------------
CREATE TABLE etl_runs (
    run_id       BIGSERIAL PRIMARY KEY,
    pipeline     TEXT        NOT NULL,
    status       TEXT        NOT NULL,   -- success | failed | running
    started_at   TIMESTAMPTZ NOT NULL,
    finished_at  TIMESTAMPTZ,
    rows_loaded  BIGINT,
    message      TEXT
);
COMMENT ON TABLE etl_runs IS 'Synthetic ETL run history.';

COMMIT;

-- =============================================================================
-- Read-only role used by the SQL Workspace and AI Analyst.
-- The application connects as this role for any user-influenced SQL.
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'xeno_readonly') THEN
        CREATE ROLE xeno_readonly LOGIN PASSWORD 'xeno_readonly_pw';
    END IF;
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO xeno_readonly', current_database());
END
$$;

GRANT USAGE  ON SCHEMA public       TO xeno_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO xeno_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO xeno_readonly;

-- Belt and braces: this role must never write, even if a GRANT is fat-fingered later.
ALTER ROLE xeno_readonly SET default_transaction_read_only = on;
ALTER ROLE xeno_readonly SET statement_timeout = '8000ms';
ALTER ROLE xeno_readonly SET idle_in_transaction_session_timeout = '15000ms';
